### ISSUE TITLE
Simple coding tasks

### ISSUE THREAD

**Issue by podarok** [drupal-ukraine/advanced_forum#28]
When #27 landed there are tasks to be done from code
1. ~~@todo $node_types = _node_types_build()->types; https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L83 and https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L100~~
2. ~~Remove/implement https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L153~~
3. Define forum containers https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L187 and https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L199
4. ~~Check image module is the same https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L206~~
5. ~~Port taxonomy vocabulary list https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L217~~
6. ~~Port field_info_instances() https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L221~~
7. ~~Convert system_get_date_types() https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L282 Simple one~~
8. ~~Set default date type  https://github.com/drupal-ukraine/advanced_forum/blob/8.x-1.x/d8/modules/custom/advanced_forum/src/Form/AdminSettingsForm.php#L292  - pre Novice )))~~

**Comment by Max-Kuzomko** [comment]
Will work on:

6), 7)

Plan to get it done by 6th of Jan.
Will keep you posted.
