### ISSUE TITLE
Migrate forum_access to D8

### ISSUE THREAD

**Issue by 32i** [drupal-ukraine/advanced_forum#48]
Quote from #2 :

> The ForumAccess module does not yet have a D8 version, although there is a ticket open for porting of it (maintainers could use support). It depends on ACL (Access Control Lists), which has an alpha1 for D8; the ACL maintainers are asking for support to finish the port.
> 
> So that is the current status of what blocks using the standard external modules. Some degree of "user access control" functionality might be helpful to build directly into this module if those are not yet stable and/or if helping bring them to a stable release might cause too much delay. Building such functionality directly into this module might not be ideal, but it would effectively circumvent the "blockers".

**Comment by annya-a** [comment]
Done. See https://www.drupal.org/node/2626178
